---
# # Install pre-commit hooks via
# pre-commit install

repos:
- repo: https://github.com/ambv/black
  rev: 21.6b0
  hooks:
  - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    additional_dependencies: ["flake8-bugbear"]
